# Generated by Django 4.1.5 on 2023-01-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BibleReviewApp', '0003_alter_biblecharacter_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biblecharacter',
            name='image',
            field=models.ImageField(upload_to='BibleReviewApp/images/'),
        ),
    ]
