# Generated by Django 5.0.7 on 2024-07-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BibleReviewApp', '0005_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='studyAgain',
            field=models.BooleanField(),
        ),
    ]
