# Generated by Django 5.0.7 on 2024-07-22 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BibleReviewApp', '0006_alter_review_studyagain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-date']},
        ),
    ]
